### ISSUE TITLE
发现慢的位置和优化思路

### ISSUE THREAD

**Issue by jiangzhonglian** [Lockvictor/MovieLens-RecSys#1]
## itemcf:
耗时分析：98.2%的时间在 
for related_movie, w in sorted(self.movie_sim_mat[movie].items(), key=itemgetter(1), reverse=True)[0:K]:

## usercf:
耗时分析：50.4%的时间在
for v, wuv in sorted(self.user_sim_mat[user].items(), key=itemgetter(1), reverse=True)[0:K]:

## 总结
至于itemcf为什么那么慢，是因为每一次一个用户到来，你要分析这个用户所有的电影的，然后找出电影对应的top N的电影。
至于usercf为什么相对比较快，是因为每一次一个用户到来，你只需要分析该用户相关的top N的用户，找出集合中的电影就行。

这就是慢的原因。

## 优化方案：
就是：itemcf 就是传入 movie而不是user，这样就OK了。

个人想法。谢谢作者的代码，写得很棒。

**Comment by Lockvictor** [comment]
感谢如此认真细致的分析
问题确实如你所说，在usercf中sorted这一句在外侧的循环，所以只执行一次，itemcf中sorted在内侧的循环，会被执行多次，这就导致比usercf多了很多运算
至于你提出的优化方案，确实可以略过用户只通过item之间的相似度实现推荐，但这里考虑了不同用户对同一个item的评分加成，所以还是得传入user

**Comment by jiangzhonglian** [comment]
🙏  明白了
