### ISSUE TITLE
Where do the recommendations go?

### ISSUE THREAD

**Issue by Mohamed3on** [Lockvictor/MovieLens-RecSys#2]
I've run the file like you instructed, however, I don't know how to actually use the recommender.
How do I test it? where are the results?

**Comment by Lockvictor** [comment]
The main focus of the program is **Modeling and Evaluating**. 
What the program does is: generating training and test set, training model, evaluating model. The results are four indicators: precision, recall, coverage and popularity, which indicate the model is good or not.
**Recommendation** is done in the step of evaluting, but my program didn't save the movies recommanded and model. If you want to see the results of recommandation, just add some code to the function of evaluating to save them.
