### ISSUE TITLE
关于算法的一些问题像您请教

### ISSUE THREAD

**Issue by Chenbaocun** [Lockvictor/MovieLens-RecSys#8]
最近在写一个音乐推荐的项目，决定采用协同过滤，目前有几个问题。
1.您的推荐算法是没有建立模型的吧，所以每次推荐都是以所有的评分数据为依托，所以对于每个用户推荐都需要进行100+秒的计算吗？
2.您的推荐算法运行结束时的返回的precision=0.3767        recall=0.0759   coverage=0.3175 popularity=6.9195分别代表什么意思，这些结果是如何计算出来的，为什么这几个结果可以用来表征推荐系统的准确度呢。这个跟实际用户的推荐结果的满意程度有挂钩吗。
3.您的算法中是否应用了一些协同过滤的改进算法，比如矩阵分解？
初学机器学习，请您赐教。

**Comment by Lockvictor** [comment]
你的问题在《推荐系统实践》里都有讲解，请仔细阅读
